# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 506cb7392576b9871e892445586882703806c52f89ebc29914a6ecd1492a58969e22a7b228d3dabb97fa51f47cbccf3668a12fe7f5b22632672d2a0ec11f66e0

test:
  secret_key_base: 245e830f99f1c3b72fe5fa142e27606db0cabe19425de069de52dbc4e00e608e4540ecc94d7184020998076a9e155aad99a88a49154304d2677cc5f8da003758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
